os: linux
dist: xenial
language: android
before_deploy: 
  - git config --local user.name "$github_name"
  - git config --local user.email "$github_email"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $travis_tag
script:
  - jdk_switcher use oraclejdk8
  - echo sdk.dir $ANDROID_HOME > local.properties
  - export TERM=dumb
  - export JAVA_OPTS="-XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError -Xmx2048m"
  - ./gradlew --stacktrace assemble
deploy:
      provider: releases
      token: $github_token
      file: play-services-core/build/outputs/apk/*/
      file_glob: true
      skip_cleanup: true
      on:
         tags: false 
android:
  components:
  - tools
  - platform-tools
  - build-tools-29.0.3
  - android-29
  - extra-android-m2repository
